const minMaxProfile= [
    "A,B,C,D",
    "A,B,C,D",
    "A,B,C,D",
    "D,C,A,B",
    "D,C,A,B",
    "A,D,B,C",
    "A,D,B,C",
    "C,B,A,D",
    "C,B,A,D",
    "B,D,A,C",
    "B,D,A,C",
    "C,A,B,D",
    "C,A,B,D",
    "D,C,A,B",
    "D,C,A,B",
    "B,A,D,C",
    "B,A,D,C"
]
const slaterProfile= [
    "A,B,C,D",
    "D,C,A,B",
    "B,C,A,D",
    "D,A,B,C",
    "D,A,B,C",
    "C,B,D,A",
    "A,C,B,D",
    "D,B,A,C",
    "B,D,A,C",
    "C,A,B,D"
];
const copelandProfile= [
    "A,D,B,C",
    "A,D,B,C",
    "A,D,B,C",
    "A,D,C,B",
    "A,D,C,B",
    "A,D,C,B",
    "B,C,A,D",
    "B,C,A,D",
    "B,C,A,D",
    "B,C,A,D",
    "D,B,C,A",
    "D,B,C,A",
    "D,B,C,A",
    "D,B,C,A",
    "D,B,C,A",
    "B,D,A,C",
    "B,D,A,C",
    "B,D,A,C",
    "B,D,A,C",
    "B,D,A,C",
    "B,D,A,C",
]
const kemenyProfile = [
    "D,A,B,C",
    "D,A,B,C",
    "D,A,C,B",
    "A,D,C,B",
    "C,A,B,D",
    "C,A,B,D",
    "A,B,D,C",
    "B,C,D,A",
    "B,C,D,A",
    "B,C,D,A",
    "B,C,A,D"
];

//TIDEMAN======================
const tidemanProfile = [
    "W,X,Z,Y",
    "W,X,Z,Y",
    "W,X,Z,Y",
    "W,X,Z,Y",
    "W,X,Z,Y",
    "W,X,Z,Y",
    "W,X,Z,Y",
    "W,Y,X,Z",
    "W,Y,X,Z",
    "X,Y,Z,W",
    "X,Y,Z,W",
    "X,Y,Z,W",
    "X,Y,Z,W",
    "X,Z,W,Y",
    "X,Z,W,Y",
    "X,Z,W,Y",
    "X,Z,W,Y",
    "X,Z,W,Y",
    "Y,W,X,Z",
    "Y,Z,W,X",
    "Y,Z,W,X",
    "Y,Z,W,X",
    "Y,Z,W,X",
    "Y,Z,W,X",
    "Y,Z,W,X",
    "Y,Z,W,X",
    "Y,Z,W,X"
]

const schulzeProfile=
[
"A,B,C,D",
"A,B,C,D",
"A,B,C,D",
"D,A,B,C",
"D,A,B,C",
"D,B,C,A",
"D,B,C,A",
"C,B,D,A",
"C,B,D,A"
]

export { minMaxProfile, slaterProfile, kemenyProfile, copelandProfile, tidemanProfile,schulzeProfile };